// npm i @types/bcrypt
// npm i @types/dotenv
// npm i @types/express
// npm i @types/jsonwebtoken
// npm i @types/multer
// npm i @types/mongoose
// npm i @types/morgan
// npm i @types/node
// npm i @types/validator